apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: demo-acc-v2
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    app.kubernetes.io/part-of: demo-acc-v2
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "11"
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/vrabbi/demo-acc-v2
      ref:
        branch: main
